version: '3.3'
services:
  web:
    image: e11y-server:latest
    command: node /app/index.js
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - '../../mongo:/growcery'

networks:
  mongo_link:
    external: true
